apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-devops-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-devops-app
  template:
    metadata:
      labels:
        app: my-devops-app
    spec:
      containers:
      - name: my-devops-app
        image: my-devops-app:latest
        imagePullPolicy: Never  # This will prevent pulling the image from a registry
        ports:
        - containerPort: 8080
