apiVersion: v1
kind: Service
metadata:
  name: my-devops-app-service
spec:
  selector:
    app: my-devops-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
